
from app import db,models
from datetime import datetime

a=models.AreaOfInterests(user_id=1, country='US', state='TX', city='Houston, TX',area='Nightclubs')
db.session.add(a)
db.session.commit()
b=models.AreaOfInterests(user_id=2,country='US', state='NY', city='New York City, NY',area='Wine Bars')
db.session.add(b)
db.session.commit()
c=models.AreaOfInterests(user_id=3,country='US', state='CA', city='San Francisco, CA',area='Museums')
db.session.add(c)
db.session.commit()
d=models.AreaOfInterests(user_id=4,country='US', state='TX', city='Houston, TX',area='Bars')
db.session.add(d)
db.session.commit()
e=models.AreaOfInterests(user_id=5,country='US', state='WA', city='Seattle, WA',area='Coffee')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=6,country='US', state='WA', city='Seattle, WA',area='Notable Restaurants')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=7,country='US', state='TX', city='Houston, TX',area='Street Food/Food Trucks')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=8,country='US', state='WA', city='Seattle, WA',area='Hiking')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=9,country='US', state='WA', city='Olympia, WA',area='Cycling')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=10,country='US', state='NC', city='Durham, NC',area='Coffee')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=11,country='US', state='NC', city='Durham, NC',area='Notable Restaurants')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=12,country='US', state='CA', city='Los Angeles, CA', area='Museums')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=13,country='US', state='CA', city='Los Angeles, CA', area='Museums')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=14,country='US', state='WI', city='Milwaukee, WI', area='Theater')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=15,country='US', state='WI', city='Madison, WI', area='Historical Sites')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=16,country='US', state='NY', city='New York City, NY', area='Luxury Stores')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=17,country='US', state='AZ', city='Phoenix, AZ', area='Brunch')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=18,country='US', state='MN', city='Minneapolis, MN', area='Spa')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=19,country='US', state='MN', city='Saint Paul, MN', area='Hiking')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=20,country='US', state='IL', city='Chicago, IL', area='Museums')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=21,country='US', state='AZ', city='Phoenix, AZ', area='Museums')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=22,country='US', state='WA', city='Seattle, WA', area='Cocktail Bars')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=23,country='US', state='HI', city='Honolulu, HI', area='Fishing')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=24,country='US', state='FY', city='Orlando, FL', area='Concerts')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=25,country='US', state='DC', city='Washintong, DC', area='Museums')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=26,country='US', state='MA', city='Boston, MA', area='Historical Sites')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=27,country='US', state='NJ', city='Newark, NJ', area='Festivals')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=28,country='US', state='NJ', city='Newark, NJ', area='Free Attractions')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=29,country='US', state='NC', city='Charlotte, NC', area='Music Scene')
db.session.add(e)
db.session.commit()
e=models.AreaOfInterests(user_id=30,country='US', state='FL', city='Miami, FL', area='Fishing')
db.session.add(e)
db.session.commit()

AOI = models.AreaOfInterests.query.all()
print (AOI)
