from app import db,models
from datetime import datetime

a=models.User(nickname='blubbyblob2', email='blubbyblob2@gmail.com', firstname='Katerina',lastname='Eigenvalue',phone='3928372837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='allanas_lifexo', email='duckduckgoose@hotmail.com', firstname='Jameson',lastname='Carpenter',phone='3928371837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='blubbyblob3', email='jqjiax99@yahoo.com', firstname='Justin',lastname='Xia',phone='4088928327',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='waterbottle', email='camelbak_user@yahoo.com', firstname='Garrick',lastname='Meister',phone='1012023345',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='mtnbkr', email='mountainbikerlvr@gmail.com', firstname='Ellen',lastname='Veladour',phone='9210128492',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='ellendegenerate', email='ellend@ellend.com', firstname='Ellen',lastname='Degeneres',phone='8329178281',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='oprahomma', email='opradabes@gmail.com', firstname='Oprah',lastname='Winfrey',phone='3928312837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='FDfcX00', email='edgyone@gmail.com', firstname='Kevin',lastname='Wu',phone='3918372837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='swagyolo_7', email='bryansilva@gmail.com', firstname='Bryan',lastname='Silva',phone='1928372837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user1', email='user1@gmail.com', firstname='Naruto',lastname='Uzumaki',phone='1928372837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user2', email='user2@gmail.com', firstname='Sasuke',lastname='Uchiha',phone='3901072827',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user3', email='naraman@gmail.com', firstname='Shikamaru',lastname='Nara',phone='8928371137',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user4', email='temarinara@gmail.com', firstname='Temari',lastname='Nara',phone='7928372837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user5', email='springsakura@gmail.com', firstname='Sakura',lastname='Haruno',phone='3925502837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user6', email='the_salad_girl@gmail.com', firstname='Sarada',lastname='Uchiha',phone='111372837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user7', email='croptopclan@gmail.com', firstname='Inojin',lastname='idk',phone='3928370000',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user8', email='idied4noreasonlol@hotmail.com', firstname='Neji',lastname='Hyuuga',phone='3958372831',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user9', email='hyuugahinata@gmail.com', firstname='Hinata',lastname='Hyuuga',phone='3999972837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user10', email='user10@gmail.com', firstname='Ten',lastname='Shi',phone='1928372837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user11', email='user11@gmail.com', firstname='Eleven',lastname='Shiyi',phone='3901072827',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user12', email='user12@gmail.com', firstname='Twelve',lastname='Shier',phone='8928371137',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user13', email='user13@gmail.com', firstname='Thirteen',lastname='Shisan',phone='7928372837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user14', email='user14@gmail.com', firstname='Fourteen',lastname='Shisi',phone='3925502837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user15', email='user15@gmail.com', firstname='Fifteen',lastname='Shiwu',phone='111372837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user16', email='user16@gmail.com', firstname='Sixteen',lastname='Shiliu',phone='3928370000',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user17', email='user17@gmail.com', firstname='Seventeen',lastname='Shiqi',phone='3958372831',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user18', email='user18@gmail.com', firstname='Eighteen',lastname='Shiba',phone='3999972837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user19', email='user19@gmail.com', firstname='Nineteen',lastname='Shijiu',phone='3999972837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user20', email='user20@gmail.com', firstname='Twenty',lastname='Ershi',phone='3999972837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()
a=models.User(nickname='user21', email='user21@gmail.com', firstname='Twentyone',lastname='Ershiyi',phone='3999972837',about_me='ipsum dolorem')
db.session.add(a)
db.session.commit()





